services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fingerseal
      POSTGRES_USER: fingerseal
      POSTGRES_PASSWORD: fingerseal
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
