server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/dataforge;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: false
  jackson:
    default-property-inclusion: non_null

app:
  encryption:
    key: ${APP_ENCRYPTION_KEY:HfuLI1phOsxsMfSfijZ03D2+QtJy3tAENrHBFfiZkNo=}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: finger-seal
