CREATE TABLE IF NOT EXISTS "connection_configs" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL,
    "DB_TYPE" VARCHAR(50) NOT NULL,
    "HOST" VARCHAR(255),
    "PORT" INT,
    "DATABASE" VARCHAR(255),
    "USERNAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255)
);
