CREATE TABLE IF NOT EXISTS "connection_configs" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL,
    "DB_TYPE" VARCHAR(50) NOT NULL,
    "HOST" VARCHAR(255),
    "PORT" INT,
    "DATABASE" VARCHAR(255),
    "USERNAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "USE_SSH_TUNNEL" BOOLEAN DEFAULT FALSE,
    "SSH_HOST" VARCHAR(255),
    "SSH_PORT" INT DEFAULT 22,
    "SSH_USER" VARCHAR(255),
    "SSH_PASSWORD" VARCHAR(255),
    "SSH_PRIVATE_KEY_PATH" VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS "query_history" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "CONNECTION_ID" BIGINT NOT NULL,
    "SQL" CLOB NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL,
    "ELAPSED_MS" BIGINT,
    "ROWS_COUNT" INT,
    "ERROR_MSG" CLOB,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
